--- #YAML:1.0
name: Net-Stomp
version: 0.32
author:
  - Leon Brocard <acme@astray.com>.
abstract: A Streaming Text Orientated Messaging Protocol Client
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
