# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-STOMP
version:      0.6
version_from: 
installdirs:  site
requires:
    IO::Select:                    0
    IO::Socket::INET:              0
    IO::Socket::SSL:               0
    List::Util:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
